[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 8.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Windowed"
title = "Alacritty"
opacity = 0.8

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

[keyboard]
bindings = [
    { key="ArrowUp", mods="Control|Shift", action="ScrollLineUp" },
    { key="ArrowDown", mods="Control|Shift", action="ScrollLineDown" }
]
